# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Weizhi (eric) Quan
# title: Senior Network System Administrator
email: erickwoncn@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  ericquan99
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: eric.kwon.180
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: weizhi-quan
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/avatar_weizhi.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Weizhi Quan and I am currently a Master of Data Science Student at University of Melbourne.

  I am most skilled in: <mark>Mathematics</mark>, <mark>Data Analysis</mark>, <mark>Machine Learning</mark>, <mark>Python</mark>, <mark>SQL</mark>
  My primary research interest is in <mark>data science</mark>, <mark>computational statistics</mark>, and <mark>machine learning</mark>.

content:

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Melbourne
        caption: February 2024 - Now
        sub_title: Master of Data Science
        quote: >
          Postera Crescam Laude
        description: | # this will include new lines to allow paragraphs
          -	Currently studying Master of Data Science at University of Melbourne.
          -	Expected to graduate in 2025.
          -	Relevant courses: Data Analysis, Machine Learning, Data Visualisation, and Big Data Management.

      - layout: left
        title: Queen's University
        caption: September 2018 - June 2023
        sub_title: Bachelor of Science (Honours)
        quote: >
          Sapientia et Doctrina Stabilitas
        description: | # this will include new lines to allow paragraphs
          -	Graduated with major in Mathematics, minor in World Language Studies, and certificate in Data Analytics.
          -	Grade of A/A+ in Real Analysis, Fundamental Statistical Inference, Topics in Data Analytics, and Statistical Learning II.
          -	senior year GPA: 3.7/4.3.


  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: American Express - Default Prediction (Competition on Kaggle)
        # link: github.com/sproogen
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Final Project for CISC 451/839 Topics in Data Analytics, Grade of 100/100 for Report, 89/100 for Presentation.
          Index Terms: Mean Absolute Deviation in Feature Engineering, Machine Learning, Data Visualization, Artificial Noise.
        description: | # this will include new lines to allow paragraphs
          Innovative methods of using MAD in feature engineering in extremely large dataset, decent amount of work in data visualizing & preprocessing, and systematic analysis among machine learning models including LGBM, XGB, LSTM & CATB.
      - layout: left
        title: Predicting a Recession Using Bond Yields with ARIMA
        # link: github.com/sproogen
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Final Project for CISC/CMPE 351 Advanced Data Analytics, Grade of 85/100 for Project.
          Index Terms: Time Series Analysis, Time Series Forecasting Method, ARIMA Model, Recession Prediction.
        description: | # this will include new lines to allow paragraphs
          Accurately predicts economic recession. Works include seasonal differencing to remove cyclic trends in time series, parameter tuning with PACF & ACF, model construction using AIC & BIC test, and possible improvements using ARMA-GARCH model.

  - title: Internship # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: POIZON Global
        link: https://www.poizon.com
        # link_text: boringcompany.com
        sub_title: Global Merchandising
        caption: September 2023 - December 2023
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          -	Coordinating between business in mainland China and business overseas.
          - Intensive use of Pivot Table to analyze data.
      - layout: left
        title: EARLY DATA Company
        link: https://www.earlydata.com/en/home_en/
        # link_text: boringcompany.com
        sub_title: Content Specialist
        caption: September 2023 - December 2023
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          -	Fundamental practice including data sorting.
          -	Programming application including using Python to run projects.
          -	Innovative projects including using Python and KNIME to maintain database and check for irregularity routinely.

  - title: Honours & Awards
    layout: list
    content: # this will include new lines to allow paragraphs
      - layout: left
        title: Queen's University
        link: https://www.poizon.com
        # link_text: boringcompany.com
        sub_title: Principle's Scholarship
        caption: September 2018
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        # description: | # this will include new lines to allow paragraphs
        #   - Intensive use of Pivot Table to analyze data.
      - layout: left
        title: Queen's University
        link: https://www.poizon.com
        # link_text: boringcompany.com
        sub_title: Dean's Honour List
        caption: Fall 2020 - Winter 2021
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        # description: | # this will include new lines to allow paragraphs
        #   - Intensive use of Pivot Table to analyze data.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
